"""Added core entities

Revision ID: 17f189b57426
Revises: 45f2342e8803
Create Date: 2026-05-18 00:19:04.693252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f189b57426'
down_revision = '45f2342e8803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cranes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crane_name', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('load_capacity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crane_name')
    )
    op.create_table('ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ship_name', sa.String(length=100), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('fuel_level', sa.Float(), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ships_ship_name'), ['ship_name'], unique=False)

    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_containers_container_id'), ['container_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_containers_container_id'))

    op.drop_table('containers')
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ships_ship_name'))

    op.drop_table('ships')
    op.drop_table('cranes')
    # ### end Alembic commands ###
