"""Added AuditLog table

Revision ID: 448bcf2096f2
Revises: 17f189b57426
Create Date: 2026-05-18 02:03:41.139019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448bcf2096f2'
down_revision = '17f189b57426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
